### PR TITLE
Add discernible classes and names to stubs

### PR DESCRIPTION
**Pull request by saxamaphone69**
Following my comment from #108, I attempted a PR.

I'm sure there is a better way to make the HTML than `innerHTML`, but it's a start.

### CODE REVIEW

**Comment by TuxedoTako** [comment]
> I'm sure there is a better way to make the HTML than `innerHTML`, but it's a start.

`subject` here is user generated, and `nameBlock` contains whatever username is used. This is vulnerable to XSS. Even when the user isn't trying to XSS, putting a `<` in one of those fields will break how it's displayed.

**Comment by saxamaphone69** [comment]
I guess as well, if stubs should look like
Subject - Anonymous (where `.stub-subject` needs `::after { content: ' - '; }`
or the `margin-right: 1ch` that's present now, with no ' - ' breaking up the subject/name.

**Comment by TuxedoTako** [comment]
I'm curious to see what you'll use these classes for.

**Comment by saxamaphone69** [comment]
Probably nothing, but glad that the option is there. Appreciate it again.

**Pull request merged**
